name: Build Development Clients

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_android_dev:
    type: build
    params:
      platform: android
      profile: development

  build_ios_dev:
    type: build
    params:
      platform: ios
      profile: development
