// Orders, products, shipments, quotes, payments, rates, suppliers, staff,
// marketplace accounts, sourcing — seed dataset for Mission Control.
import type {
  AdminMarketplaceAccount,
  AdminOrder,
  AdminPayment,
  AdminProduct,
  AdminQuote,
  AdminRate,
  AdminShipment,
  AdminSourcingRequest,
  AdminStaffMember,
  AdminSupplier,
} from "./types";
import { daysAgo, hoursAgo, minutesAgo, it } from "./seed";

export const SEED_ORDERS: AdminOrder[] = [
  { id: "o1", reference: "CS-2026-00124", customer_id: "c1", customer_name: "Mohamed Abdi", customer_phone: "+252 63 412 0001", city: "Hargeisa", status: "in_transit", shipping_method: "air", payment_method: "zaad", payment_status: "confirmed", items: [it("i1a", "p1", "Wireless Earbuds TWS Pro", 2, 18, "Black"), it("i1b", "p2", "Smartwatch Series 9", 1, 280, "Silver")], total_usd: 842, shipping_usd: 145, weight_kg: 1.2, tracking: [{ status: "Payment confirmed", location: "Online", time: daysAgo(6) }, { status: "Purchased from supplier", location: "Yiwu, China", time: daysAgo(5) }, { status: "Arrived at China warehouse", location: "Yiwu Warehouse", time: daysAgo(3) }, { status: "Inspection completed", location: "Yiwu Warehouse", time: daysAgo(3) }, { status: "Consolidated for shipping", location: "Yiwu Warehouse", time: daysAgo(2) }, { status: "Shipped — Air freight", location: "Guangzhou Airport", time: daysAgo(2) }, { status: "In transit", location: "Dubai (DXB)", time: daysAgo(1) }], notes: "Customer requested discreet packaging.", created_at: daysAgo(6), updated_at: hoursAgo(2), eta: daysAgo(-2) },
  { id: "o2", reference: "CS-2026-00123", customer_id: "c2", customer_name: "Asma Hassan", customer_phone: "+252 90 555 0102", city: "Mogadishu", status: "awaiting_payment", shipping_method: "sea", payment_method: "edahab", payment_status: "pending", items: [it("i2a", "p3", "Industrial Stand Mixer 20L", 4, 320), it("i2b", "p4", "Stainless Steel Cookware Set", 8, 95)], total_usd: 2_140, shipping_usd: 380, weight_kg: 64.5, created_at: hoursAgo(8), updated_at: hoursAgo(2), eta: daysAgo(-32) },
  { id: "o3", reference: "CS-2026-00122", customer_id: "c4", customer_name: "Hodan Abdi", customer_phone: "+252 61 333 4421", city: "Hargeisa", status: "out_for_delivery", shipping_method: "air", payment_method: "bank_transfer", payment_status: "confirmed", items: [it("i3a", "p5", "Hotel Linen Set King", 24, 78)], total_usd: 2_010, shipping_usd: 138, weight_kg: 42.1, tracking: [{ status: "Payment confirmed", location: "Online", time: daysAgo(9) }, { status: "Shipped — Air freight", location: "Guangzhou", time: daysAgo(5) }, { status: "Arrived in Somaliland", location: "Hargeisa", time: daysAgo(1) }, { status: "Out for delivery", location: "Hargeisa Branch", time: hoursAgo(2) }], created_at: daysAgo(9), updated_at: hoursAgo(2), eta: hoursAgo(-12) },
  { id: "o4", reference: "CS-2026-00121", customer_id: "c3", customer_name: "Liban Farah", customer_phone: "+252 65 778 8090", city: "Bosaso", status: "delivered", shipping_method: "sea", payment_method: "zaad", payment_status: "confirmed", items: [it("i4a", "p6", "Power Bank 20000mAh", 3, 22)], total_usd: 198, shipping_usd: 42, weight_kg: 1.6, created_at: daysAgo(40), updated_at: daysAgo(8), eta: daysAgo(11) },
  { id: "o5", reference: "CS-2026-00120", customer_id: "c5", customer_name: "Faisal Nur", customer_phone: "+252 64 901 1155", city: "Garowe", status: "in_warehouse", shipping_method: "air", payment_method: "premier_wallet", payment_status: "confirmed", items: [it("i5a", "p7", "Men's Casual Sneakers", 5, 24, "Black/42"), it("i5b", "p8", "LED Desk Lamp", 6, 11)], total_usd: 322, shipping_usd: 58, weight_kg: 5.4, created_at: daysAgo(3), updated_at: hoursAgo(12), eta: daysAgo(-5) },
  { id: "o6", reference: "CS-2026-00119", customer_id: "c6", customer_name: "Sahra Ali", customer_phone: "+252 90 779 0033", city: "Mogadishu", status: "delivered", shipping_method: "sea", payment_method: "bank_transfer", payment_status: "confirmed", items: [it("i6a", "p9", "Bulk Towels 12-pack", 40, 14)], total_usd: 1_400, shipping_usd: 240, weight_kg: 96.0, created_at: daysAgo(60), updated_at: daysAgo(20), eta: daysAgo(15) },
  { id: "o7", reference: "CS-2026-00118", customer_id: "c1", customer_name: "Mohamed Abdi", customer_phone: "+252 63 412 0001", city: "Hargeisa", status: "customs", shipping_method: "air", payment_method: "zaad", payment_status: "confirmed", items: [it("i7a", "p10", "Laptop Stand Aluminum", 2, 32)], total_usd: 184, shipping_usd: 38, weight_kg: 2.2, created_at: daysAgo(7), updated_at: hoursAgo(3), eta: hoursAgo(-2) },
  { id: "o8", reference: "CS-2026-00117", customer_id: "c2", customer_name: "Asma Hassan", customer_phone: "+252 90 555 0102", city: "Mogadishu", status: "paid", shipping_method: "sea", payment_method: "edahab", payment_status: "confirmed", items: [it("i8a", "p11", "Commercial Blender 1500W", 6, 142)], total_usd: 1_120, shipping_usd: 220, weight_kg: 38.0, created_at: hoursAgo(20), updated_at: hoursAgo(4), eta: daysAgo(-30) },
  { id: "o9", reference: "CS-2026-00116", customer_id: "c4", customer_name: "Hodan Abdi", customer_phone: "+252 61 333 4421", city: "Hargeisa", status: "refunded", shipping_method: "air", payment_method: "bank_transfer", payment_status: "refunded", items: [it("i9a", "p12", "Damaged carton received", 1, 280)], total_usd: 312, shipping_usd: 32, weight_kg: 1.0, created_at: daysAgo(15), updated_at: daysAgo(4) },
  { id: "o10", reference: "CS-2026-00115", customer_id: "c5", customer_name: "Faisal Nur", customer_phone: "+252 64 901 1155", city: "Garowe", status: "cancelled", shipping_method: "sea", payment_method: "cash", payment_status: "failed", items: [it("i10a", "p13", "Camping Tent 4-Person", 2, 110)], total_usd: 280, shipping_usd: 60, weight_kg: 8.0, created_at: daysAgo(20), updated_at: daysAgo(15) },
  { id: "o11", reference: "CS-2026-00114", customer_id: "c3", customer_name: "Liban Farah", customer_phone: "+252 65 778 8090", city: "Bosaso", status: "draft", shipping_method: "air", payment_method: "zaad", payment_status: "pending", items: [], total_usd: 0, shipping_usd: 0, weight_kg: 0, created_at: hoursAgo(3), updated_at: hoursAgo(3) },
  { id: "o12", reference: "CS-2026-00113", customer_id: "c6", customer_name: "Sahra Ali", customer_phone: "+252 90 779 0033", city: "Mogadishu", status: "delivered", shipping_method: "air", payment_method: "bank_transfer", payment_status: "confirmed", items: [it("i12a", "p14", "Restaurant Plates Set", 30, 18)], total_usd: 720, shipping_usd: 110, weight_kg: 36.0, created_at: daysAgo(35), updated_at: daysAgo(8) },
  { id: "o13", reference: "CS-2026-00112", customer_id: "c7", customer_name: "Safia Noor", customer_phone: "+252 65 770 0011", city: "Hargeisa", status: "delivered", shipping_method: "air", payment_method: "zaad", payment_status: "confirmed", items: [it("i13a", "p6", "Power Bank 20000mAh", 1, 22)], total_usd: 64, shipping_usd: 18, weight_kg: 0.6, created_at: daysAgo(28), updated_at: daysAgo(14) },
  { id: "o14", reference: "CS-2026-00111", customer_id: "c8", customer_name: "Yusuf Adan", customer_phone: "+252 61 220 7799", city: "Mogadishu", status: "in_transit", shipping_method: "sea", payment_method: "edahab", payment_status: "confirmed", items: [it("i14a", "p3", "Industrial Stand Mixer 20L", 2, 320), it("i14b", "p4", "Stainless Steel Cookware Set", 4, 95)], total_usd: 1_320, shipping_usd: 280, weight_kg: 48.0, created_at: daysAgo(5), updated_at: hoursAgo(8), eta: daysAgo(-22) },
  { id: "o15", reference: "CS-2026-00110", customer_id: "c4", customer_name: "Hodan Abdi", customer_phone: "+252 61 333 4421", city: "Hargeisa", status: "purchasing", shipping_method: "air", payment_method: "bank_transfer", payment_status: "confirmed", items: [it("i15a", "p15", "USB-C Fast Charger 65W", 20, 13), it("i15b", "p8", "LED Desk Lamp", 10, 11)], total_usd: 410, shipping_usd: 68, weight_kg: 6.8, created_at: hoursAgo(4), updated_at: hoursAgo(1) },
  { id: "o16", reference: "CS-2026-00109", customer_id: "c1", customer_name: "Mohamed Abdi", customer_phone: "+252 63 412 0001", city: "Hargeisa", status: "awaiting_payment", shipping_method: "air", payment_method: "usdt", payment_status: "pending", items: [it("i16a", "p2", "Smartwatch Series 9", 2, 280, "Silver"), it("i16b", "p1", "Wireless Earbuds TWS Pro", 4, 18, "Black")], total_usd: 632, shipping_usd: 95, weight_kg: 1.5, created_at: minutesAgo(20), updated_at: minutesAgo(20) },
  { id: "o17", reference: "CS-2026-00108", customer_id: "c7", customer_name: "Safia Noor", customer_phone: "+252 65 770 0011", city: "Hargeisa", status: "delivered", shipping_method: "air", payment_method: "zaad", payment_status: "confirmed", items: [it("i17a", "p16", "Kids Cartoon Backpack", 2, 12)], total_usd: 64, shipping_usd: 14, weight_kg: 1.0, created_at: daysAgo(50), updated_at: daysAgo(40) },
];
